### ISSUE TITLE
how to view a save point_clound file

### ISSUE THREAD

**Issue by userkenny** [3dtof/voxelsdk-examples#1]
Hi sir,

To this voxelsdk_example & after a successful compile. I wrote a simple command such as 
./DepthCapture -v 0x0bda -p 0x5825 -f test.pcd -n 1 -t pointcloud
few questions here
1. Did my file save as a right extension as test.pcd?
2. which compiled PCL program is able to open this saved file format to view? is it pcl_viewer or others? any command text example?
3 if I saved a 30 frames in another pointcloud file. which PCL programs is able to view or stream it as a video? pcl_viewer?
Thank you.

**Comment by Arrowana** [comment]
If you have a PCD file use pcl_viewer_release.exe in PCL binary folder
